name: Release Builds
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checking out branch
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
  
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          
        run: |
          echo $ENCODED_STRING
          echo $ANDROID_KEY_PASSWORD
          echo $ANDROID_KEY_ALIAS
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > sign
      
      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
      
      # - name: Build Release apk
      #   env:
      #     ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #     ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      #   run: ./gradlew assembleRelease --stacktrace

      # - name: Build Release bundle
      #   env:
      #     ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #     ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      #   run: ./gradlew bundleRelease --stacktrace

      # - name: Get release file aab path
      #   id: releaseAab
      #   run: echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_OUTPUT

      # - name: Get release file apk path
      #   id: releaseApk
      #   run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      # - name: Zip Files
      #   uses: papeloto/action-zip@v1
      #   with:
      #     files: ${{ steps.releaseAab.outputs.aabfile }} ${{ steps.releaseApk.outputs.apkfile }}
      #     dest: ${{ steps.releaseApk.outputs.apkfile }}.zip
          
      # - name: Upload Release Build to Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #      name: release-artifacts
      #      path: ${{ steps.releaseApk.outputs.apkfile }}
